### ISSUE TITLE
Suggestions on reproducibility and portability

### ISSUE THREAD

**Issue by shenwei356** [KennthShang/PhaGCN#9]
Hi Jiayu, I'd like to run PhaGCN and some other tools from your team. But I found it's not easy to set up.

For PhaGCN, there are some known issues:

1. Before installation

        # HOWTO: edit environment.yaml: change value of 'name' and 'prefix'.
    
2. Installation

        # ISSUE: nothing provides __glibc >=2.17,<3.0.a0 needed by cudatoolkit-11.1.1-h6406543_10
        # HOWTO: update mamba/conda first.
    
3. Running

        error: python: relocation error: /lib64/libpthread.so.0: symbol __h_errno, version GLIBC_PRIVATE not defined in file libc.so.6 with link time referenc conda    
        # HOWTO: run the two lines below, or append the two lines below to ~/.bashrc or miniconda3/envs/phagcn/etc/profile.d/conda.sh
        export LD_PRELOAD=/lib64/libpthread.so.0
        export LD_PRELOAD=/lib64/libc.so.6
    
4. Making the threads of DIAMOND configurable. Hard-coded parameters make the script less portable.

        Option 1: Manually edit '8' to other values
        Option 2: add an option --threads
    
        #     parser.add_argument('--threads', type=int, default=40)
        #     make_diamond_cmd = 'diamond makedb --threads {:d} --in database/Caudovirales_protein.fasta -d database/database.dmnd'.format(args.threads)
        #     diamond_cmd = 'diamond blastp --threads {:d} --sensitive -d database/database.dmnd -q database/Caudovirales_protein.fasta -o database/database.self-diamond.tab'.format(args.threads)

5. Allowing `run_Speed_up.py` to be runnable in other paths, not just the project home. I tried to edit it but later found there is more than one file to edit. I'd suggest making the output and temporary files configurable via the command line option. And also let the python path find other scripts and database path automatically, so it could be used to process multiple input files simultaneously.

Wei

**Comment by KennthShang** [comment]
Hi Wei,

Sorry for the confusion. The first three problems can be solve using the following command lines:

```
conda env create -f environment.yaml -n phagcn
conda activate phagcn
```

Each time you want to run PhaGCN, you need to activate it first. For the Cuda problem, you need to check which version you have installed on your machine and then install [PyTorch](https://pytorch.org/) with the corresponding version.

For problems 3 and 4, I have updated the program to incorporate the parameters.

For problem 5, thanks for your suggestions. Because this is one of my early works, I did not notice such a need. Recently, I have maintained all my programs for phage tasks and will release a more comprehensive one-shot program, which allows users to run more automatically. Since I am on vacation leave, I will upload the program as soon as possible. But it still depends on my network. Maybe within a week, I suppose.

Thanks again.

Best,
Jiayu

**Comment by KennthShang** [comment]
Hi, 

I am glad to let you know that our web server for phage-related tasks (including phage identification, taxonomy classification, lifestyle prediction, and host prediction) is available! You can visit [PhaBOX](https://phage.ee.cityu.edu.hk/) to use the GUI. We also provided more detailed intermediate files and visualization for further analyzation. 

A stand-alone version of PhaBOX is also available via [GitHub version](https://github.com/KennthShang/PhaBOX), and you can run all these tools at once. The new program is runnable in other paths.

Hope you will enjoy it!

Best,
Jiayu
